version: '3'
services:
  groovy-postgresql:
    image: postgres
    volumes:
      - groovy_db:/var/lib/postgresql
      - groovy_data:/var/lib/postgresql/data
    networks:
      - groovy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - groovy-postgresql
    networks:
      - groovy
volumes:
  groovy_data:
  groovy_db:

networks:
  groovy:

